name: "Pull Request Labeler"
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: paulfantom/periodic-labeler@master
      continue-on-error: true
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        LABEL_MAPPINGS_FILE: .github/labeler.yml


